#!/usr/bin/env python3
#
# =============================================================================================
# IBM Confidential
# (C) Copyright IBM Corp. 2020
# The source code for this program is not published or otherwise divested of its trade secrets,
# irrespective of what has been deposited with the U.S. Copyright Office.
# =============================================================================================
#

"""
This script adds the hash to the "Genctl Release Git Hash" field in a Jira ticket by parsing specific information contained
within the gitdiff.txt file that is generated by the update-slack-releases.yaml task (in the "slack-output" directory).
"""

###############################################################################
# I M P O R T S ###############################################################
###############################################################################

import requests
import json
import re
import argparse
import sys
import logging
from http import HTTPStatus

##############
# CONSTANTS
##############

# Regex to match Jira issue
# JIRA issues consist of "ProjectKey-IssueNumber", where:
# ProjectKey has the following minimum restrictions:
# - The first character must be a letter
# - The key must consist of length 2 or greater
# - All letters used in the project key must be from the Modern Roman Alphabet and upper case
# - Only letters, numbers or the underscore character can be used
# - It can be customized to be more restrictive than the above
# IssueNumber has the following restrictions:
# - The pattern for an issue's number is immutable (cannot be customized), and must be a number: [0-9]+

# Note: This Jira pattern was verified as the one currently in use (as of 3/11/20),
# hence there not being an underscore character
JIRA_PATTERN = re.compile('[A-Z][A-Z0-9]+-[0-9]+')
# Regex to match git sha e.g. a178835de8e350c09cb10d208ecea14ed9356c72
GIT_SHA_PATTERN = re.compile('[0-9a-f]{40}')

# Jira issue and project rest endpoint.
# Detailed info can be found here https://developer.atlassian.com/server/jira/platform/rest-apis/
ISSUE_API = "/rest/api/3/issue/"
PROJECT_API = "/rest/api/3/project"

# GLOBALS
logger = None


###############################################################################
# F U N C T I O N S ###########################################################
###############################################################################

def setup_logger(debug_enabled=False):
    """
    * Setup up the logger and return a handle
    """
    # set the logger to show the time/level/message
    # stdout logging is sufficient

    handler = logging.StreamHandler()
    formatter = logging.Formatter('%(asctime)s %(levelname)s: %(message)s')
    # This gives more info for debugging
    # formatter = logging.Formatter('%(asctime)s {%(funcName)s:%(lineno)d} %(levelname)s: %(message)s')
    handler.setFormatter(formatter)

    logger_setup = logging.getLogger()
    logger_setup.addHandler(handler)
    logger_setup.setLevel(logging.DEBUG if debug_enabled is True else logging.INFO)
    logger_setup.info("Logger level set to \"{}\"".format(logger_setup.level))

    return logger_setup


def parse_args():
    """
    Parse the arguments passed when calling this file.
    :return:
    """
    parser = argparse.ArgumentParser(description="Parser to take required and optional values for the script")
    parser.add_argument('-f', '--file', help="Location of the gitdiff.txt file", required=True, dest="filename")
    parser.add_argument('-u', '--username', help="Jira Username", required=True, dest="username")
    parser.add_argument('-p', '--password', help="Jira Password", required=True, dest="password")
    parser.add_argument('-j', '--jira-url', help="Jira URL (with port)", required=True, dest="jira_url")
    parser.add_argument('-e', '--cert-file', help="The full path to the certificate", required=True, dest="cert")
    parser.add_argument('-d', '--debug', help="When used, enables debug mode. No args", required=False,
                        dest="debug", default=False, action='store_true')
    args = parser.parse_args()
    return args


def main():
    """
    Main function, determines what the script should do when called
    """
    # Setup variables
    args = parse_args()
    filename = args.filename
    auth = (args.username, args.password)
    cert_file = args.cert
    jira_url = args.jira_url
    debug = args.debug

    ##################
    # CONSTANTS
    ##################

    global logger

    #####################
    # COMMANDS
    #####################

    logger = setup_logger(debug)

    verify_jira_status(jira_url, auth, cert_file)  # Checks that Jira is available, throws error if not
    genctl_release_sha, jira_ids = parse_genctl_release_hash_and_jira_ticket(filename)
    valid_tickets, invalid_tickets = check_jira_project(jira_url, jira_ids, auth, cert_file)
    for invalid_ticket in invalid_tickets:
        logger.error("{} is not a valid ticket".format(invalid_ticket))
    add_genctl_release_sha_to_tickets(jira_url, genctl_release_sha, valid_tickets, auth, cert_file)
    logger.info("Script completed successfully")


def verify_jira_status(jira_url, auth, cert_file):
    """
    Verifies that Jira is up and can be connected to. Exits with error if unable to
    :param auth: username/password tuple
    :param jira_url: Jira server URL
    :param cert_file: auth info for connecting to jira
    :return:
    """
    try:
        logger.debug("Verifying connection to jira endpoint \"{}\"".format(jira_url))
        jira_check = requests.head(jira_url, auth=auth, verify=cert_file)
        if jira_check.status_code != HTTPStatus.OK:
            logger.error("Status code {} != {}".format(str(jira_check.status_code), str(HTTPStatus.OK)))
            logger.info("Please check that the login credentials & configuration are still valid. "
                        "Potential sources of the issue may be: username, password, permission level")
            sys.exit(1)
    except requests.exceptions.RequestException as e:
        logger.error("Jira server \"{}\" cannot be reached.".format(jira_url))
        logger.error(e)
        sys.exit(1)


def get_jira_projects(jira_url, auth, cert_file):
    """
    Gets the list of Jira Projects from the Jira server.
    :return project_list:
    """
    project_list = []
    project_url = jira_url + PROJECT_API
    try:
        projects = requests.get(project_url, auth=auth, verify=cert_file)
        projects.raise_for_status()
    except requests.exceptions.RequestException as e:
        logger.error("requests error encountered")
        logger.error(e)
        sys.exit(1)
    for project in projects.json():
        project_list.append(project['key'])
    return project_list


def parse_genctl_release_hash_and_jira_ticket(genctl_release_jira_file):
    """
    Parses the file containing the information about the git hash and jira ticket
    :param genctl_release_jira_file: The file containing the Jira ID(s) and genctl-release git hash
    :return (genctl release sha, jira id list):
    """

    try:
        # After the code running under the "with" command is out of scope, "open_file" is automatically closed
        with open(genctl_release_jira_file, 'r') as open_file:
            lines = open_file.read()
    except IOError as e:
        logger.error("Failed to open {} in read mode".format(genctl_release_jira_file))
        logger.error(e)
        sys.exit(1)

    # Output the file name and its contents - this makes it easy to look into the causes of any issues.
    logger.info("File \"{}\"  contents:\n{}".format(genctl_release_jira_file, lines))

    # Get genctl hash
    genctl_release_sha = re.findall(GIT_SHA_PATTERN, lines)

    # Get Jira all jira tickets from the commit and remove trailing or preceding whitespaces
    jira_id_list = re.findall(JIRA_PATTERN, lines)
    jira_id_list = [x.strip(' ') for x in jira_id_list]

    # Remove any potential duplicates by converting to a set then back to a list
    jira_id_list = list(set(jira_id_list))

    # Do checks on values
    if not genctl_release_sha:
        logger.error("Unable to find Genctl Release Git Hash in \"{}\"".format(genctl_release_jira_file))
        sys.exit(1)
    if not jira_id_list:
        logger.error("Unable to find Jira Ticket id in \"{}\"".format(genctl_release_jira_file))
        sys.exit(1)
    # Return the values to the caller
    return genctl_release_sha[0], jira_id_list


def build_requests_data(genctl_release_sha):
    """
    :param genctl_release_sha:
    :return:
    """
    jira_genctl_sha_field = "customfield_12100"
    if genctl_release_sha:
        data = {"fields": {jira_genctl_sha_field: genctl_release_sha}}
        logger.info("Genctl Release Git Hash is \"{}\"".format(genctl_release_sha))
        return data
    else:
        logger.error("The Genctl Release Git Hash passed was empty")
        sys.exit(1)


def check_jira_project(jira_url, jira_id_list, auth, cert_file):
    """
    Checks that each jira ticket has a valid jira project.
    :param jira_url: url to jira
    :param jira_id_list: List of Jira Tickets
    :param auth: username/password tuple
    :param cert_file: auth info for connecting to jira
    :return (valid_jira_ids, invalid_jira_ids):
    """

    jira_project_list = get_jira_projects(jira_url, auth, cert_file)

    # Setup an array to contain jira tickets that are valid projects, and those that are not.
    invalid_jira_ids = []
    valid_jira_ids = []

    # If the Jira project is in the Jira project list, add to valid_jira_ids, otherwise add to invalid_jira_ids
    for jira_id in set(jira_id_list):
        # Get the jira project key from the issue id. For example in issue id JIRA-123, JIRA is the project key
        jira_project = jira_id.split("-")[0]

        if jira_project in jira_project_list:
            # Log that the Jira project was valid for the ticket
            logger.info("The Jira Project \"{}\" was found for \"{}\"".format(jira_project, jira_id))
            valid_jira_ids.append(jira_id)
        else:
            # Log an error that there was an invalid Jira Project for the ticket
            logger.error("The Jira Project \"{}\" was not contained in the list of "
                         "valid Jira Projects (for \"{}\").".format(jira_project, jira_id))
            invalid_jira_ids.append(jira_id)
    return valid_jira_ids, invalid_jira_ids


def add_genctl_release_sha_to_tickets(jira_url, genctl_release_sha, jira_tickets, auth, cert_file):
    """
    Adds the genctl sha to the tickets passed to it
    :param auth: username/password tuple
    :param jira_url: the url to jira
    :param genctl_release_sha: The genctl sha to add to the jira ticket
    :param jira_tickets: The list of jira tickets to add the genctl sha to
    :param cert_file: auth info for connecting to jira
    """
    # Check that we actually have a jira ticket
    if len(jira_tickets) == 0:
        logger.error("There were no valid jira tickets defined to add the Genctl Release Git Hash to")
        sys.exit(1)  # Exit if not; We continue after error below since we could have more valid tickets to process
    errors_encountered = False
    html_header = {'Content-Type': 'application/json'}
    requests_genctl_release_data = build_requests_data(genctl_release_sha)
    for jira in set(jira_tickets):
        api_url = jira_url + ISSUE_API + jira
        logger.info("Adding Genctl Release Git Hash to \"{}\"".format(jira))
        try:
            response = requests.put(
                api_url,
                headers=html_header,
                data=json.dumps(requests_genctl_release_data),
                auth=auth,
                verify=cert_file
            )
            if response.status_code == HTTPStatus.NO_CONTENT:
                logger.info("Successfully added Genctl Release Git Hash \"{}\" to \"{}\"".format(genctl_release_sha, jira))
            else:
                logger.error("Failed to add \"{}\" to the Genctl Release Git Hash field in the Jira Ticket \"{}\""
                             .format(genctl_release_sha, jira))
                logger.error("Status code was \"{}\"".format(str(response.status_code)))
                if response.status_code == HTTPStatus.BAD_REQUEST:
                    logger.warning("Some possibilities for the status code are:\n"
                                   " - The Jira Project did not have the \"Genctl Release Git Hash\" field available\n"
                                   " - The Jira Issue's 'type' doesn't allow the Genctl Release Git Hash field")  # e.g. "Feature"
                # If we we didn't or weren't able to handle an error, set a var saying we had errors
                errors_encountered = True

        except requests.exceptions.RequestException as e:
            logger.error("requests error encountered!")
            logger.error(e)
            sys.exit(1)
    logger.info("Finished attempt(s) to upload Genctl Release Git Hash to valid ticket(s)")
    if errors_encountered:
        logger.error("Error(s) were encountered")
        sys.exit(1)


###############################################################################
# M A I N #####################################################################
###############################################################################


if __name__ == "__main__":
    main()
