version: '2'

tasks:
  pr-code-checks:
    include:
      - dind
    displayName: 01-misc-scans
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail        
        script: |
          #!/usr/bin/env bash

          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24                    
          ${PATH_TO_PIPELINE}/steps/misc-scans.sh

      - name: detect-secrets
        include:
          - docker-socket
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        when: 'false'
  
  pr-code-checks-2:
    include:
      - dind
    displayName: 02-unit-tests
    runtimeClassName: large
    from: pr-code-checks
    steps:
      - name: checks-setup
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24        
          ${PATH_TO_PIPELINE}/steps/test.sh
      - name: compliance-checks
        when: 'false'

  pr-code-checks-3:
    include:
      - dind
    displayName: 03-static-scan
    runtimeClassName: large
    from: pr-code-checks
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: continue
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24        
          ${PATH_TO_PIPELINE}/steps/static-scan.sh
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        when: 'false'
  
  pr-code-checks-4:
    include:
      - dind
    runAfter:
      - pr-code-checks  #misc-scans-task-1
      - pr-code-checks-2  #unit-test-task-2
    displayName: 04-build-amd64-images-ubuntu22
    runtimeClassName: large
    from: pr-code-checks
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        when: 'false'
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash          
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24
          export BUILD_ARTIFACT_TYPE="images"
          export BASE_IMAGE_VERSION="ubuntu22"
          ${PATH_TO_PIPELINE}/steps/build_amd64_artifacts.sh "BUILD_AMD64_IMAGES_UBUNTU22"
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        when: 'false'
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24
          export BASE_IMAGE_VERSION="ubuntu22"
          ${PATH_TO_PIPELINE}/steps/compliance-checks.sh

  pr-code-checks-5:
    include:
      - dind
    displayName: 05-build-amd64-packages-ubuntu22
    runtimeClassName: large
    from: pr-code-checks
    runAfter:
      - pr-code-checks  #misc-scans-task-1
      - pr-code-checks-2  #unit-test-task-2
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24
          export BUILD_ARTIFACT_TYPE="packages"
          export BASE_IMAGE_VERSION="ubuntu22"
          ${PATH_TO_PIPELINE}/steps/build_amd64_artifacts.sh "BUILD_AMD64_PACKAGES_UBUNTU22"
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        when: 'false'
  
  pr-code-checks-6:
    include:
      - dind
    runAfter:
      - pr-code-checks  #misc-scans-task-1
      - pr-code-checks-2  #unit-test-task-2
    displayName: 06-build-amd64-images-ubuntu24
    runtimeClassName: large
    from: pr-code-checks
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:24.20260817071520
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash          
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24
          export BUILD_ARTIFACT_TYPE="images"
          export BASE_IMAGE_VERSION="ubuntu24"
          ${PATH_TO_PIPELINE}/steps/build_amd64_artifacts.sh "BUILD_AMD64_IMAGES_UBUNTU24"
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:24.20260817071520
        onError: continue
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24
          export BASE_IMAGE_VERSION="ubuntu24"
          ${PATH_TO_PIPELINE}/steps/compliance-checks.sh

  pr-code-checks-7:
    include:
      - dind
    displayName: 07-build-amd64-packages-ubuntu24
    runtimeClassName: large
    from: pr-code-checks
    runAfter:
      - pr-code-checks  #misc-scans-task-1
      - pr-code-checks-2  #unit-test-task-2
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:24.20260817071520
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24
          export BUILD_ARTIFACT_TYPE="packages"
          export BASE_IMAGE_VERSION="ubuntu24"
          ${PATH_TO_PIPELINE}/steps/build_amd64_artifacts.sh "BUILD_AMD64_PACKAGES_UBUNTU24"
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        when: 'false'
  
  pr-code-checks-8:
    include:
      - dind
    displayName: 08-build-s390x-images-ubuntu22
    runtimeClassName: large
    from: pr-code-checks
    runAfter:
      - pr-code-checks  #misc-scans-task-1
      - pr-code-checks-2  #unit-test-task-2      
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        when: 'false'
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24
          export BUILD_ARTIFACT_TYPE="images"
          export BASE_IMAGE_VERSION="ubuntu22"
          ${PATH_TO_PIPELINE}/steps/build_s390x_images.sh
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        when: 'false'
  
  pr-code-checks-9:
    include:
      - dind
    displayName: 09-build-s390x-packages-ubuntu22
    runtimeClassName: large
    from: pr-code-checks
    runAfter:
      - pr-code-checks  #misc-scans-task-1
      - pr-code-checks-2  #unit-test-task-2
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24
          export BUILD_ARTIFACT_TYPE="packages"
          export BASE_IMAGE_VERSION="ubuntu22"
          ${PATH_TO_PIPELINE}/steps/build_s390x_packages.sh
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        when: 'false'

  pr-code-checks-10:
    include:
      - dind
    displayName: 10-build-s390x-images-ubuntu24
    runtimeClassName: large
    from: pr-code-checks
    runAfter:
      - pr-code-checks  #misc-scans-task-1
      - pr-code-checks-2  #unit-test-task-2      
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:24.20260817071520
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24
          export BUILD_ARTIFACT_TYPE="images"
          export BASE_IMAGE_VERSION="ubuntu24"
          ${PATH_TO_PIPELINE}/steps/build_s390x_images.sh
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        when: 'false'
  
  pr-code-checks-11:
    include:
      - dind
    displayName: 11-build-s390x-packages-ubuntu24
    runtimeClassName: large
    from: pr-code-checks
    runAfter:
      - pr-code-checks  #misc-scans-task-1
      - pr-code-checks-2  #unit-test-task-2
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:24.20260817071520
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24
          export BUILD_ARTIFACT_TYPE="packages"
          export BASE_IMAGE_VERSION="ubuntu24"
          ${PATH_TO_PIPELINE}/steps/build_s390x_packages.sh
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        when: 'false'
  
  pr-code-checks-12:
    include:
      - dind
    displayName: 12-create-manifest
    runAfter:
      - pr-code-checks-4  #build-amd64-images-ubuntu22
      - pr-code-checks-8  #build-s390x-images-ubuntu22
      - pr-code-checks-6  #build-amd64-images-ubuntu24
      - pr-code-checks-10  #build-s390x-images-ubuntu24
    from: pr-code-checks
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24          
          ${PATH_TO_PIPELINE}/steps/manifest.sh
      - name: detect-secrets
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: compliance-checks
        when: 'false'

finally:  
  code-pr-finish:
    steps:
      - name: run-stage
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_dev_integration_v11_ubuntu22_and_24          
          ${PATH_TO_PIPELINE}/steps/pr-finish.sh
