version: '2'

# CI Pipeline: code-checks, code-build, deploy-checks, deploy-release
tasks:
  code-checks:
    include:
      - dind
    # code-checks includes five configurable steps: setup, detect-secrets, compliance-checks, peer-review, static-scan
    displayName: auto-semver-task-1
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        script: |
          #!/usr/bin/env bash

          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/artifacts/merge_v11          
          ${PATH_TO_PIPELINE}/steps/auto_semver.sh

      - name: detect-secrets
        include:
          - docker-socket
        onError: stopAndFail
      
      - name: compliance-checks
        when: 'false'
      
      - name: static-scan
        when: 'false'
  
  code-checks-2:
    include:
      - dind
    # code-checks includes five configurable steps: setup, detect-secrets, compliance-checks, peer-review, static-scan
    displayName: static-scan-task-2
    runAfter:
      - code-checks
    from: code-checks
    steps:
      - name: checks-setup
        when: 'false'

      - name: detect-secrets
        when: 'false'
      
      - name: peer-review        
        when: 'false'
      
      - name: compliance-checks
        when: 'false'      
      
      - name: static-scan
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: continue
        include:
          - docker-socket
        script: |
          #!/bin/sh
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/artifacts/merge_v11
          ${PATH_TO_PIPELINE}/steps/code-static-scan.sh
  
  code-checks-3:
    include:
      - dind
    # code-checks includes five configurable steps: setup, detect-secrets, compliance-checks, peer-review, static-scan
    from: code-checks
    displayName: unit-tests-task-3
    runAfter:
      - code-checks #autosemver-task-1 
    steps:      
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        include:
          - docker-socket
        onError: stopAndFail
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/artifacts/merge_v11
          ${PATH_TO_PIPELINE}/steps/unit_tests.sh

      - name: compliance-checks
        when: 'false'
      
      - name: detect-secrets        
        when: 'false'          
      
      - name: peer-review        
        when: 'false'
      
      - name: static-scan        
        when: 'false'

  code-checks-4:
    include:
      - dind
    # code-checks includes five configurable steps: setup, detect-secrets, compliance-checks, peer-review, static-scan
    from: code-checks
    displayName: build-amd64-images-task-4
    runAfter:
      - code-checks #autosemver-task-1
    steps:      
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash

          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/artifacts/merge_v11
          export BUILD_ARTIFACT_TYPE="images"
          ${PATH_TO_PIPELINE}/steps/build_amd64_artifacts.sh

      - name: compliance-checks
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        include:
          - docker-socket
        onError: stopAndFail
        script: |
          #!/bin/sh
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/artifacts/merge_v11
          ${PATH_TO_PIPELINE}/steps/compliance-checks.sh
      
      - name: detect-secrets        
        when: 'false'          
      
      - name: peer-review        
        when: 'false'
      
      - name: static-scan        
        when: 'false'
  
  code-checks-5:
    include:
      - dind
    # code-checks includes five configurable steps: setup, detect-secrets, compliance-checks, peer-review, static-scan
    from: code-checks
    displayName: build-amd64-packages-task-5
    runAfter:
      - code-checks #autosemver-task-1 
    steps:      
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        include:
          - docker-socket
        onError: stopAndFail
        script: |
          #!/usr/bin/env bash

          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/artifacts/merge_v11
          export BUILD_ARTIFACT_TYPE="packages"
          ${PATH_TO_PIPELINE}/steps/build_amd64_artifacts.sh

      - name: compliance-checks
        when: 'false'
      
      - name: detect-secrets        
        when: 'false'          
      
      - name: peer-review        
        when: 'false'
      
      - name: static-scan        
        when: 'false'
  
  code-checks-6:
    include:
      - dind
    from: code-checks
    displayName: create-manifest-task-6
    runAfter:
      - code-checks-4
      - code-checks-5
    # code-checks includes five configurable steps: setup, detect-secrets, compliance-checks, peer-review, static-scan
    steps:      
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        include:
          - docker-socket
        onError: stopAndFail
        script: |
          #!/usr/bin/env bash

          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/artifacts/merge_v11
          ${PATH_TO_PIPELINE}/steps/manifest.sh

      - name: detect-secrets
        when: 'false'

      - name: compliance-checks
        when: 'false'
      
      - name: peer-review
        when: 'false'
      
      - name: static-scan
        when: 'false'

  code-build:    
    include:
      - dind
    runAfter:
      - code-checks-6 #create-manifest-task
    displayName: scan-artifacts-task-7    
    # code-build includes five configurable steps: setup, unit-test, build-artifact, sign-artifact, scan-artifact
    steps:
      - name: setup        
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        include:
          - docker-socket
        onError: stopAndFail
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/artifacts/merge_v11
          ${PATH_TO_PIPELINE}/steps/save_artifacts.sh
      - name: unit-test
        when: 'false'
      - name: build-artifact
        when: 'false'
      - name: sign-artifact
        when: 'false'
      - name: scan-artifact
        include:
          - docker-socket
        onError: stopAndFail        
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        script: |
          #!/bin/sh
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/artifacts/merge_v11
          ${PATH_TO_PIPELINE}/steps/scan_artifact.sh

  deploy-checks:
    when: false

  deploy-release:
    include:
      - dind
    runAfter:
      - deploy-checks
    displayName: deploy-release-task-8
    # deploy-release includes one configurable step: run-stage
    steps:
      - name: run-stage
        onError: stopAndFail
        inlcude:
          - docker-socket
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/artifacts/merge_v11
          ${PATH_TO_PIPELINE}/steps/release.sh
  

finally:
  code-ci-finish:
    steps:
      - name: run-stage
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        script: |
          #!/usr/bin/env bash

          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi
          echo "Running code-ci-finish"
          exit 0
