$schema: http://json-schema.org/draft-07/schema#
type: object
required:
  - apps
properties:
  apps:
    type: object
    required:
      - feature_flags
    additionalProperties: false
    properties:
      feature_flags:
        type: object
        required:
          - vpc
        additionalProperties: false
        properties:
          api_spec_version:
            type: string
            additionalProperties: false
          vpc:
            type: array
            uniqueItems: true
            items:
              type: object
              required:
                - name
                - "on"
                - off_variation
                - default
              additionalProperties: false
              properties:
                name: 
                  type: string
                "on":
                  type: boolean
                retirement_date:
                  type: string
                  format: date
                off_variation: {}
                default:
                  type: object
                  required:
                    - variation_value
                  properties:
                    variation_value: {}
                  additionalProperties: false
                rules:
                  type: array
                  uniqueItems: true
                  items:
                    type: object
                    required:
                      - clauses
                      - variation_value
                    additionalProperties: false
                    properties:
                      clauses:
                        type: array
                        uniqueItems: true
                        items:
                          type: object
                          required:
                            - attribute
                            - op
                            - values
                          additionalProperties: false
                          properties:
                            attribute:
                              type: string
                              enum:
                              - key
                              - region
                              - bssAccount
                              - envName
                              - datacenter
                              - mzone
                              - availabilityZone
                              - serviceId
                              - customKey
                              - requestMethod
                              - resourceType
                            op:
                              type: string
                              enum:
                              - in
                              - lessThan
                              - lessThanOrEqual
                              - greaterThan
                              - greaterThanOrEqual
                              - endsWith
                              - startsWith
                              - contains
                              - matches
                            values:
                              type: array
                              uniqueItems: true
                              items: {}
                            negate:
                              type: boolean
                              default: false
                      variation_value: {}