version: '2'

tasks:
  pr-code-checks:
    include:
      - dind
    displayName: 01-detect-secrets
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail        
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11
          ADD_BRANCH_PROTECTION_RULES="$(get_env add-branch-protection-rules)"
          if [ "${ADD_BRANCH_PROTECTION_RULES}" = "1" ]; then
            echo "Applying branch protection rules to ${BASE_BRANCH}"
            ${PATH_TO_GENCTL_CI}/onepipeline/utils/setup_branch_protection.sh
          elif [ "${ADD_BRANCH_PROTECTION_RULES}" = "0" ]; then
            echo "Application of branch protection rules disabled"
          else
            echo "Invalid value present in env var add-branch-protection-rules, either 0 or 1"
            exit 1
          fi
      - name: detect-secrets
        include:
          - docker-socket
      - name: compliance-checks
        when: 'false'
      - name: static-scan
        when: 'false'

  pr-code-checks-2:
    include:
      - dind
    from: pr-code-checks
    runAfter:
      - pr-code-checks
    displayName: 02-misc-scans
    steps:
      - name: checks-setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail        
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11
          ${PATH_TO_PIPELINE}/steps/misc-scans.sh
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: static-scan
        when: 'false'
  
  pr-code-checks-3:
    include:
      - dind
    from: pr-code-checks
    runAfter:
      - pr-code-checks
      - pr-code-checks-2
    displayName: 03-static-scan
    steps:
      - name: checks-setup
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: static-scan
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: continue
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11
          ${PATH_TO_PIPELINE}/steps/code-static-scan.sh
  
  pr-code-checks-4:
    include:
      - dind    
    displayName: 04-code-compliance-checks
    from: pr-code-checks
    runAfter:
      - pr-code-checks
      - pr-code-checks-2
    steps:
      - name: checks-setup
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533        
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11
          ${PATH_TO_PIPELINE}/steps/compliance-checks.sh
      - name: static-scan
        when: 'false'
    
  pr-code-build:
    include:
      - dind
    displayName: 05-unit-tests
    runAfter:
      - pr-code-checks
      - pr-code-checks-2
    steps:
      - name: setup
        when: 'false'
      - name: unit-test
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11
          ${PATH_TO_PIPELINE}/steps/unit-tests.sh
      - name: build-artifact
        when: 'false'
      - name: sign-artifact
        when: 'false'
      - name: scan-artifact
        when: 'false'

  pr-code-build-2:
    include:
      - dind
    displayName: 06-scan-artifacts
    from: pr-code-build
    runAfter:
      - pr-code-build
    steps:
      - name: setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail        
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11
          ${PATH_TO_PIPELINE}/steps/save_artifacts.sh          
      - name: unit-test
        when: 'false'
      - name: build-artifact
        when: 'false'
      - name: sign-artifact
        when: 'false'
      - name: scan-artifact
        include:
          - docker-socket
        onError: stopAndFail
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        script: |
          #!/bin/sh
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11
          ${PATH_TO_PIPELINE}/steps/scan_artifact.sh
  
  pr-deploy-checks:
    include:
      - dind
    displayName: 07-blast-radius-tests
    runAfter:      
      - pr-code-build
      - pr-code-build-2
    steps:
      - name: deploy
        when: 'false'
      - name: acceptance-test
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11
          ${PATH_TO_PIPELINE}/steps/acceptance_tests.sh

  pr-deploy-checks-2:
    include:
      - dind    
    displayName: 08-auto-merge
    from: pr-deploy-checks
    runAfter:
      - pr-deploy-checks
    steps:
      - name: deploy
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail        
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11          
          ${PATH_TO_PIPELINE}/steps/finish.sh
      - name: acceptance-test
        when: 'false'      

  pr-deploy-checks-3:
    include:
      - dind
      - step-extension
    displayName: 09-sign-artifacts-and-deploy-process
    from: pr-deploy-checks
    runAfter:
      - pr-deploy-checks-2
    steps:
      - name: deploy
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail        
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11          
          ${PATH_TO_PIPELINE}/steps/deploy.sh
      - name: step-extension
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        displayName: sign-artifacts-and-add-inventory
        onError: stopAndFail
        runAfter:
          - deploy
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11
          ${PATH_TO_PIPELINE}/steps/sign_artifacts_and_add_inventory.sh
      - name: acceptance-test
        when: 'false'

  pr-deploy-checks-4:
    include:
      - dind 
      - step-extension
    displayName: 10-dynamic-scan
    from: pr-deploy-checks
    runAfter:
      - pr-deploy-checks-3
    steps:
      - name: deploy
        when: 'false'
      - name: step-extension
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        displayName: dynamic-scan
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/pr_and_ci_master_v11          
          ${PATH_TO_PIPELINE}/steps/dynamic_scan.sh
      - name: acceptance-test
        when: 'false' 

finally:  
  app-preview-pr-finish:
    steps:
      - name: run-stage
        onError: stopAndFail
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        script: |
          #!/usr/bin/env bash

          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi
          echo "Running app-preview-pr-finish"
          exit 0
