version: '1'

setup:
  dind: true
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533-amd64
  abort_on_failure: true
  script: |
    #!/usr/bin/env bash

    export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
    export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/release_bundles/pr
    # Run common PR checks first (cancellation and branch protection)
    ${PATH_TO_GENCTL_CI}/onepipeline/jobs/onepipeline_common_pr_checks.sh
    ${PATH_TO_PIPELINE}/steps/setup.sh
test:
  # The main reason we do abort_on_failure: false here is because we are on a PR pipeline and we want to reach code-pr-finish
  # code-pr-finish is the stage where One-Pipeline will set the GHE status check for this stage (code-unit-tests)
  # In addition, running the compliance-checks is a shift left not waiting until the build/unit tests pass early checking stuff like vulnerabilities
  abort_on_failure: false
  dind: true
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533-amd64
  script: |
    #!/usr/bin/env bash

    export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
    export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/release_bundles/pr
    ${PATH_TO_PIPELINE}/steps/test.sh
deploy-ng-as-subpipeline:
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533-amd64
  dind: true
  abort_on_failure: true
  image_pull_policy: IfNotPresent
  script: |
    #!/usr/bin/env bash
    export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
    export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/release_bundles/pr
    ${PATH_TO_PIPELINE}/steps/deploy_ng_as_subpipeline.sh
deploy-ngdc-as-subpipeline:
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533-amd64
  dind: true
  abort_on_failure: true
  image_pull_policy: IfNotPresent
  script: |
    #!/usr/bin/env bash
    export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
    export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/release_bundles/pr
    ${PATH_TO_PIPELINE}/steps/deploy_ngdc_as_subpipeline.sh
compliance-checks:
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533-amd64
  dind: true
  abort_on_failure: false
  image_pull_policy: IfNotPresent
  script: |
    #!/bin/sh
    export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
    export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/release_bundles/pr
    ${PATH_TO_PIPELINE}/steps/compliance-checks.sh
