# Documentation on available configuration
# https://pages.github.ibm.com/one-pipeline/docs/custom-scripts.html

version: '1'

setup:
  abort_on_failure: true
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
  script: |
    #!/usr/bin/env bash
    
    export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
    export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/merge_master_with_deploy_dal
    ${PATH_TO_PIPELINE}/steps/setup.sh
deploy:
  abort_on_failure: true
  dind: true
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
  script: |
    #!/usr/bin/env bash
    
    export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
    export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/merge_master_with_deploy_dal
    ${PATH_TO_PIPELINE}/steps/deploy.sh
deploy-dal-as-subpipeline:
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
  dind: true
  abort_on_failure: true
  image_pull_policy: IfNotPresent
  script: |
    #!/usr/bin/env bash
    export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
    export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/merge_master_with_deploy_dal
    ${PATH_TO_PIPELINE}/steps/deploy_dal_as_subpipeline.sh
cluster-validation-as-subpipeline:
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
  dind: true
  abort_on_failure: true
  image_pull_policy: IfNotPresent
  script: |
    #!/usr/bin/env bash
    export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
    export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/merge_master_with_deploy_dal
    ${PATH_TO_PIPELINE}/steps/cluster_validation_as_subpipeline.sh
qz2-cluster-validations:
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260320065041
  dind: true
  abort_on_failure: false
  image_pull_policy: IfNotPresent
  script: |
    #!/usr/bin/env bash
    export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
    export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/templatized/razee/merge_master_with_deploy_dal
    ${PATH_TO_PIPELINE}/steps/cluster_validations_brt_prerequisites.sh
    
acceptance-test:
  image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
  script: |
    #!/usr/bin/env bash
    echo "Nothing to do here"
    exit 0
