# =============================================================================================
# IBM Confidential
# (C) Copyright IBM Corp. 2021
# The source code for this program is not published or otherwise divested of its trade secrets,
# irrespective of what has been deposited with the U.S. Copyright Office.
# =============================================================================================
#
# Description: Creates a vetted versions file used in the razee hotifx
#
# Env:
#    BASE_ENVIRONMENT_PATH: Path to the base environment file
#    PRE_INTEGRATION_VETTED_VERSIONS_PATH: Path to the pre integration file (Used to get the smotainer info)
#    VETTED_VERSIONS_PATH: The path to the file that will be generated by the script
#
# Use:
#    python3 create_razee_hotfix_vetted_version_file.py.py

import yaml

from ci_python_tools import general_tools

SMOTAINER_RELEASE_KEY = 'smotainer-release'

def load_yaml(file_path):
    with open(file_path) as f:
        dictionary = yaml.safe_load(f)

    return dictionary

def save_yaml(file_path, yaml_dict):
    with open(file_path, 'w') as outfile:
        yaml.dump(yaml_dict, outfile, default_flow_style=False)

def get_version_from_bundle(bundle):
    # Declare empty result
    result = ''

    # If there is version on the root level, take it, if not take it from the first run
    if 'version' in bundle:
        result = bundle['version']
    else:
        result = bundle['runs'][0]['version']

    return result

def get_result_file_contents(base,pre_integration):
    # Generate the skeleton of the contents
    result = {
        'version': {}
    }

    # Iterate over the bundles and add to the version
    for bundle in base['apps']['release_bundles']:
        result['version'][bundle['name']] = get_version_from_bundle(bundle)
    
    # Add the smotainer version
    result['version'][SMOTAINER_RELEASE_KEY] = pre_integration['version'][SMOTAINER_RELEASE_KEY]

    return result

def main():
    # Define the mandatory args
    mandatory_args = [
        'BASE_ENVIRONMENT_PATH',
        'PRE_INTEGRATION_VETTED_VERSIONS_PATH'  ,
        'VETTED_VERSIONS_PATH'
    ]

    # Parse args
    args = general_tools.parse_env(mandatory_args)

    # Load the YAML content of the base file
    base = load_yaml(args['base_environment_path'])

    # Load the YAML content of the pre integration
    pre_integration = load_yaml(args['pre_integration_vetted_versions_path'])

    # Get YAML object with the contents that will be dumped
    result = get_result_file_contents(base,pre_integration)

    # Dump
    save_yaml(args['vetted_versions_path'],result)

if __name__ == "__main__":
    main()
