##
## =============================================================================================
## IBM Confidential
## © Copyright IBM Corp. 2020
## The source code for this program is not published or otherwise divested of its trade secrets,
## irrespective of what has been deposited with the U.S. Copyright Office.
## =============================================================================================
##

# Note: This task depends on setup-dep-structure having been run prior to this task in order to setup "prepared-repo"
# This task outputs the build directory to be used in a later task that has docker available in it.
---
platform: linux

inputs:
- name: genctl-ci-repo
- name: prepared-repo # created by setup-dep-env.yaml

outputs:
- name: build

params:
  GO_DIR: prepared-repo
  CC_ARTIFACTORY_READER: ((clgitchk-artifactory-username))
  CC_ARTIFACTORY_READER_APIKEY: ((clgitchk-artifactory-token))
  GIT_PRIVATE_KEY: ((ghe-private-key))

run:
  path: /bin/bash
  args:
  - -euc
  - |
    # build_root for local use
    build_root="${PWD}"
    # BUILD_ROOT to be able to be utilized by repos
    export BUILD_ROOT="${PWD}"

    # check the go version
    go version

    # setup var for the repo directory
    repo_dir=$(cat ${GO_DIR}/repo_dir)

    # Set up ssh config
    eval "$(ssh-agent -s)"
    ssh-add - <<< "$(echo "$GIT_PRIVATE_KEY" |sed '/^[[:space:]]*$/d; s/^[[:space:]]*//g')"
    mkdir -p ~/.ssh
    ssh-keyscan github.ibm.com >> ~/.ssh/known_hosts

    # Now that the required structure for dep has been setup, and that we've ensured our vars won't be overwritten, run the repos build.sh file
    # We should be at the entrypoint (build_root) before passing to the repo's build script, similar to where the repo would be if we had called a task file for the build
    # This is because we pass the "GO_DIR" var to the repo, which indicates the directory where the structure for dep starts
    echo "call hack/ci/build-cbuild.sh"
    ${repo_dir}/hack/ci/build-cbuild.sh
